const Images = {
    aboutBg : require('../Images/about-bg.jpg'),
    doctor1 : require('../Images/doctor1.jpg'),
    doctor2 : require('../Images/doctor2.jpg'),
    doctor3 : require('../Images/doctor3.jpg'),
    doctor4 : require('../Images/doctor4.jpg'),
    scope1 : require('../Images/scope1.jpg'),
    scope2 : require('../Images/scope2.jpg'),
    scope3 : require('../Images/scope3.jpg'),
    scope4 : require('../Images/scope4.jpg'),
    training : require('../Images/training.jpg'),
    homeResearch : require('../Images/home-research.jpg'),
    patient1 : require('../Images/patient-corner1.jpg'),
    patient2 : require('../Images/patient-corner2.jpg'),
    patient3 : require('../Images/patient-corner3.jpg'),
    patient4 : require('../Images/patient-corner4.jpg'),
    logo : require('../Images/ddcLogo.png'),
   
  
    single : require('../Images/single.jpg'),
    aboutSingle : require('../Images/about-single.jpg'),
    serviceDetail : require('../Images/service-detail.jpg'),
    welcome : require('../Images/welcome.jpg'),
    blog1 : require('../Images/news1.jpg'),
    blog2 : require('../Images/news2.jpg'),
    blog3 : require('../Images/news3.jpg'),
    blog4 : require('../Images/stockphoto.jpg'),
    blog5 : require('../Images/stataicsScope.jpg'),
    blog6 : require('../Images/pexels.jpg'),
    chindrenHealth : require('../Images/childrens-health.jpg'),
    training1 : require('../Images/training1.jpg'),
    training2 : require('../Images/training2.jpg'),
    training3 : require('../Images/training3.jpg'),
    training4 : require('../Images/training4.jpg'),
    training5 : require('../Images/training5.jpg'),
    globe: require('../Images/globe.png'),
    user: require('../Images/user.png'),
    balance: require('../Images/balance.png'),
    bulb: require('../Images/bulb.png'),
    group: require('../Images/group.png'),
    honesty: require('../Images/honesty.png'),
    team: require('../Images/team.png'),
    target: require('../Images/target.png'),

}

export default Images;